name: build-image CI
on:
  push:
    branches:
      - fix-ci-cd-build

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "node_api:19"
      DEFAULT_VALUE: "latest"
    steps:
      - uses: actions/checkout@v3
        with:
          dockerfile: Dockerfile
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run "${IMAGE_NAME}"
      - run: docker image build --tag=sparkew74/api_node:"${DEFAULT_VALUE}" ./
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sparkew74
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push if on `main`
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: sparkew74/api_node:"${DEFAULT_VALUE}"



